flounder: A memset parameter cause GCC5 crash.
error: 'memset' used with constant zero length parameter; this could be due to transposed parameters [-Werror=memset-transposed-args]

For more, please see section 7.21.1 of the C99 standard